#!/bin/bash
########################################################
# Written to be used on 64 bits computers
# Written By    :       Vinod Kumar
########################################################
# Enable root for Ubuntu Version
sudo echo "greeter-show-manual-login=true " >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
sudo passwd root
echo "################ root-enable Sucessfully ######################"
